Updates from Mayari

diff --git a/local/bin/git-reparent b/local/bin/git-reparent
--- a/local/bin/git-reparent
+++ b/local/bin/git-reparent
@@ -1,6 +1,6 @@
 #!/bin/bash
 # Try to rebase the current branch onto a new parent.
-# wren gayle romano <wrengr@x.com>                  ~ 2021.08.12
+# wren gayle romano <wrengr@cpan.org>               ~ 2021.11.14
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 # N.B., by naming this as we have and having it on our path, this
 # script will be automagically run if someone says `git reparent`;
@@ -8,11 +8,20 @@
 
 # TODO: Add a flag to toggle color for the error messages
 # TODO: Add flags for verbose mode & for dryrun mode
-# TODO: allow NEW_PARENT to be a commit-id, rather than forcing it to be a branch-id. And if it's a commit-id, then skip the final `git branch --set-upstream-to=` part. (Perhaps using a different executable name, if we can't automatically distinguish between the two cases.)
-# TODO: cf., <https://github.com/MarkLodato/git-reparent> for doing better about commuting patches rather than the git bs about applying diffs. <http://git.661346.n2.nabble.com/Announcing-git-reparent-tp7574982p7575061.html>
-# TODO: cf., <https://stackoverflow.com/a/5344979> about a safer way to do the rebase--onto without risking damage to the original unrebased branch.  We should prolly refactor that into this script in order to automate recovery in the event of rebase failure.
+# TODO: allow NEW_PARENT to be a commit-id, rather than forcing it
+# to be a branch-id. And if it's a commit-id, then skip the final
+# `git branch --set-upstream-to=` part. (Perhaps using a different
+# executable name, if we can't automatically distinguish between the
+# two cases.)
+# TODO: cf., <https://github.com/MarkLodato/git-reparent> for doing
+# better about commuting patches rather than the git bs about applying
+# diffs.  <http://git.661346.n2.nabble.com/Announcing-git-reparent-tp7574982p7575061.html>
+# TODO: cf., <https://stackoverflow.com/a/5344979> about a safer
+# way to do the rebase--onto without risking damage to the original
+# unrebased branch.  We should prolly refactor that into this script
+# in order to automate recovery in the event of rebase failure.
 if [[ $# -ne 1 ]]; then
-    cat << __END_USAGE__
+    >&2 cat << __END_USAGE__
 Usage: ${0##*/} NEW_PARENT
 
 Change the parent of the current branch to NEW_PARENT. This will not only
